<!-- 
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
    <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px" size="medium"
      @submit.native.prevent>
      <el-form-item label="商户id" prop="input107929">
        <el-input v-model="formData.input107929" type="text" placeholder="123456" clearable></el-input>
      </el-form-item>
      <el-form-item label="商户名称" prop="input76570">
        <el-input v-model="formData.input76570" type="text" placeholder="商户名称与营业执照保持一致，个体工商户不能以公司结尾       0/20"
          clearable></el-input>
      </el-form-item>
      <el-form-item label="账号" prop="input44247">
        <el-input v-model="formData.input44247" type="text" placeholder="18321573639" clearable></el-input>
      </el-form-item>
      <el-form-item label="所在地区" prop="input95135">
        <el-input v-model="formData.input95135" type="text" placeholder="上海市/奉贤区" clearable></el-input>
      </el-form-item>
      <el-form-item label="商户logo" prop="pictureupload49401">
        <el-upload :file-list="pictureupload49401FileList" :headers="pictureupload49401UploadHeaders"
          :data="pictureupload49401UploadData" list-type="picture-card" show-file-list :limit="3"><template
            #tip>
            <div class="el-upload__tip">可自定义为商户logo(建议200px*200PX)</div>
          </template> <template #default><i class="el-icon-plus"></i></template></el-upload>
      </el-form-item>
    </el-form>
    
  </template>
  
  <script>
    export default {
      components: {},
      props: {},
      data() {
        return {
          formData: {
            input107929: "",
            input76570: "",
            input44247: "",
            input95135: "",
            pictureupload49401: null,
          },
          rules: {},
          pictureupload49401FileList: [],
          pictureupload49401UploadHeaders: {},
          pictureupload49401UploadData: {},
        }
      },
      computed: {},
      watch: {},
      created() {},
      mounted() {},
      methods: {
        submitForm() {
          this.$refs['vForm'].validate(valid => {
            if (!valid) return
            //TODO: 提交表单
          })
        },
        resetForm() {
          this.$refs['vForm'].resetFields()
        }
      }
    }
    
  </script>
  
  <!-- <style lang="scss">
    .el-input-number.full-width-input,
    .el-cascader.full-width-input {
      width: 100% !important;
    }
    
    .el-form-item--medium {
      .el-radio {
        line-height: 36px !important;
      }
      
      .el-rate {
        margin-top: 8px;
      }
    }
    
    .el-form-item--small {
      .el-radio {
        line-height: 32px !important;
      }
      
      .el-rate {
        margin-top: 6px;
      }
    }
    
    .el-form-item--mini {
      .el-radio {
        line-height: 28px !important;
      }
      
      .el-rate {
        margin-top: 4px;
      }
    }
    
    .clear-fix:before,
    .clear-fix:after {
      display: table;
      content: "";
    }
    
    .clear-fix:after {
      clear: both;
    }
    
    .float-right {
      float: right;
    }
    
  </style>
  
  <style lang="scss" scoped>
    div.table-container {
      table.table-layout {
        width: 100%;
        table-layout: fixed;
        border-collapse: collapse;
  
        td.table-cell {
          display: table-cell;
          height: 36px;
          border: 1px solid #e1e2e3;
        }
      }
    }
    
    div.tab-container {}
    
    .label-left-align ::v-deep .el-form-item__label {
      text-align: left;
    }
    
    .label-center-align ::v-deep .el-form-item__label {
      text-align: center;
    }
    
    .label-right-align ::v-deep .el-form-item__label {
      text-align: right;
    }
    
    .custom-label {}
    
    .static-content-item {
      min-height: 20px;
      display: flex;
      align-items: center;
  
      ::v-deep .el-divider--horizontal {
        margin: 0;
      }
    }
    
  </style> -->